[Helm Chart] add configuration for spring application json
opensrp/fhir-gateway pull request #46
Opened 2023-10-04 09:32 UTC by bennsimon

- Add spring application json config option.

2023-10-04 09:40 UTC, dubdabasoduba approved these changes

2023-10-04 10:00 UTC, ndegwamartin commented on charts/fhir-gateway/values.yaml
> +  tag: "v0.1.39"
v0.1.40 for this cc @dubdabasoduba  ?

2023-10-05 06:52 UTC, ndegwamartin approved these changes

2023-10-05 11:43 UTC, ndegwamartin requested changes

2023-10-05 11:43 UTC, ndegwamartin commented on charts/fhir-gateway/values.yaml
> +  tag: "v0.1.39"
```suggestion
  tag: "v0.1.40"
```

2023-10-05 11:46 UTC, ndegwamartin approved these changes

2023-10-05 11:46 UTC, merged